language: c

addons:
  ssh_known_hosts: www2.tzurl.org

env:
  - TZDB_VERSION=2020b

script:
- make tzrearguard zoneinfo

before_install:
  - sudo apt-get -y install lzip

before_deploy:
- openssl aes-256-cbc -K $encrypted_ee29b6fba62b_key -iv $encrypted_ee29b6fba62b_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  script: ./website/upload.sh
  skip_cleanup: true
  on:
    branch: master
